name: Keep HuggingFace Space Alive

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  ping-space:
    runs-on: ubuntu-latest
    steps:
      - name: Ping HuggingFace Space with token
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          URL="https://huggingface.co/spaces/myleyu/mysol"
          echo "Pinging $URL"
          RESULT=$(curl -s -H "Authorization: Bearer $HF_TOKEN" -o /dev/null -w "%{http_code} %{time_total}" "$URL")
          echo "Result: $RESULT"
